version: '3'
services:
  facade:
    image: facade
    container_name: facade
    restart: on-failure
    depends_on:
      - rabbitMq
    ports:
      - "8080:8080"


  account:
    image: account
    container_name: account
    restart: on-failure
    depends_on:
      - rabbitMq

        
  report:
    image: report
    container_name: report
    restart: on-failure
    depends_on:
      - rabbitMq

  payment:
    image: payment
    container_name: payment
    restart: on-failure
    depends_on:
      - rabbitMq

  token:
    image: token
    container_name: token
    restart: on-failure
    depends_on:
      - rabbitMq

  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq_container
    ports:
      - "5672:5672"
      - "15672:15672"
